# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'CAP Days 2018'
tagline:          'CAP Days'
description:      'Workshop August 28th - August 31st 2018'
location:         'University of Siegen'
url:              https://homalg-project.github.io
baseurl:          /capdays-2018


exclude: [ "LICENSE.hyde.md", "README.hyde.md" ]
include: [ ]
